DROP TABLE IF EXISTS Orders;
DROP TABLE IF EXISTS Customers;
DROP TABLE IF EXISTS Products;

CREATE TABLE Products (
[ID] int primary key,
[Name] nvarchar(100),
[Price] money
);
CREATE TABLE Customers (
[ID] int primary key,
[FirstName] nvarchar(50),
[LastName] nvarchar(50),
[CardNumber] int
);
CREATE TABLE Orders (
[ID] int,
[ProductID] int,
[CustomerID] int,
PRIMARY KEY ([ID]),
FOREIGN KEY ([ProductID]) REFERENCES Products([ID]),
FOREIGN KEY ([CustomerID]) REFERENCES Customers([ID])
);
go

--add at least three records into each table
INSERT INTO Products ([ID], [Name], [Price]) VALUES (1, N'Dozen Eggs', 1.99);
INSERT INTO Products ([ID], [Name], [Price]) VALUES (2, N'Bacon Package', 3.50);
INSERT INTO Products ([ID], [Name], [Price]) VALUES (3, N'Cinnamon Rolls', 2.99);

INSERT INTO Customers ([ID], [FirstName], [LastName], [CardNumber]) VALUES (1, N'Bob', N'Builder', 1234567890);
INSERT INTO Customers ([ID], [FirstName], [LastName], [CardNumber]) VALUES (2, N'Charlie', N'Chaplin', 2345678901);
INSERT INTO Customers ([ID], [FirstName], [LastName], [CardNumber]) VALUES (3, N'David', N'Davido', 3456789012);

INSERT INTO Orders ([ID], [ProductID], [CustomerID]) VALUES (1, 2, 3);
INSERT INTO Orders ([ID], [ProductID], [CustomerID]) VALUES (2, 1, 2);
INSERT INTO Orders ([ID], [ProductID], [CustomerID]) VALUES (3, 3, 1);

--add product iphone at price $200
INSERT INTO Products ([ID], [Name], [Price]) VALUES (4, N'iPhone', 200);

--add customer tina smith
INSERT INTO Customers ([ID], [FirstName], [LastName], [CardNumber]) VALUES (4, N'Tina', N'Smith', 4567890123);

--create order tina smith bought an iphone
INSERT INTO Orders ([ID], [ProductID], [CustomerID]) VALUES (4, 4, 4);

--report all orders by tina smith
select *
from Orders
where CustomerID = 4;

--report all revenue generated by sale of iphones
select SUM(Price)
from Products
	join Orders on Orders.ProductID = Products.ID
where ProductID = 4;

--increase price of iphones to 250
update Products
set Products.Price = 250
where Products.ID = 4;